FROM ros:humble-cuda12

USER $USER
WORKDIR /home/$USER
ADD --chown=$UID:$GID docker/ufactory*.AppImage /home/$USER/ufactory.AppImage
RUN /home/$USER/ufactory.AppImage --appimage-extract && mkdir -p /home/$USER/.UFACTORY

VOLUME ["/home/$USER/.UFACTORY"]
ENTRYPOINT ["vglrun", "/bin/bash", "-i", "-c"]
CMD ["vglrun /home/${USER}/squashfs-root/ufactory-studio-client --no-sandbox --display=${DISPLAY} --allow-file-access-from-files"]
